name: Pull and Convert Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0"

jobs:
  pull-and-convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: 'VirgilClyne/GetSomeFries'
          path: 'httpdns'

      - uses: actions/checkout@v4
        with:
          repository: 'zacred0rryn/anti-ip-attribution'
          path: 'ip-attr'

      - uses: actions/checkout@v4
        with:
          repository: 'zacred0rryn/srs-custom'
          ref: 'yaml2json'
          path: 'y2j'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          pip install pyyaml

      - name: Set Up
        run: |
          mkdir -p tmp/convert
          cp y2j/convert.py tmp/convert/
          rm -r y2j

      - name: HTTP DNS
        run: |
          cp httpdns/ruleset/HTTPDNS.Block.yaml tmp/convert/httpdns-block.yaml
          rm -r httpdns

      - name: IP Attribution
        run: |
          cd ip-attr/generated
          for file in rule-provider-*; do
            newname="${file/rule-provider-/ip_attribution-}"
            mv "$file" "$newname"
          done
          cd ../..
          cp ip-attr/generated/* tmp/convert/
          rm -r ip-attr

      - name: Convert
        run: |
          cd tmp/convert && python ./convert.py && cd ../..
          mkdir -p source
          cp tmp/convert/*.json source/
          rm -r tmp && ls -l source

      - name: Check and Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if git diff --cached --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
            git commit -m "Update source format srs" -a
          fi

      - name: Push
        if: env.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Trigger Compilation
        if: env.changes == 'true'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/zacred0rryn/srs-custom/actions/workflows/compile.yml/dispatches \
            -d '{"ref":"main"}'
